name: PR Creation Automation from Release to Main

on:
  push:
    branches:
      - 'release-*'

jobs:
  cherry-pick-commit-to-main:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write

    steps:
    - name: Checkout the code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Git
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"

    - name: Extract Commit SHA from the push event
      id: get_commit_sha
      run: echo "commit_sha=${{ github.event.head_commit.id }}" >> $GITHUB_ENV


    - name: Extract Branch Name
      id: extract_branch_name
      run: |
        branch_name=${{ github.ref }}
        branch_name=${branch_name#refs/heads/}
        echo "branch_name=${branch_name}" >> $GITHUB_ENV

    - name: Create a new branch for cherry-picking
      run: |
        git checkout main
        git pull origin main
        git checkout -b "cherry-pick-${{ env.commit_sha }}"

    - name: Cherry-pick the commit onto the new branch
      run: |
        git cherry-pick ${{ env.commit_sha }} || {
          git checkout --theirs . &&
          git add . &&
          git cherry-pick --continue || git cherry-pick --skip
        }

    # make the name of the branch a variable
    - name: Push the new branch to origin
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}
      run: |
        git push origin cherry-pick-${{ env.commit_sha }}

    # - name: Create Pull Request for the cherry-picked commit
    #   id: create_pr
    #   uses: peter-evans/create-pull-request@v6
    #   with:
    #     branch: cherry-pick-${{ env.commit_sha }}
    #     base: main
    #     title: Cherry-pick commit ${{ env.commit_sha }} from ${{ env.branch_name }} to main
    #     body: |
    #       This PR cherry-picks commit ${{ env.commit_sha }} from ${{ env.branch_name }} into the main branch.
    #     labels: automated-pr

    # - name: Output Pull Request URL
    #   run: echo "Pull request URL ${{ steps.create_pr.outputs.pull-request-url }}"


