name: PR Creation Automation from Release to Main

on:
  push:
    branches:
      - 'release-*'

jobs:
  cherry-pick-commit-to-main:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write

    steps:
    - name: Checkout the code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Git
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"

    - name: Extract Commit SHA from the push event
      id: get_commit_sha
      run: echo "commit_sha=${{ github.event.head_commit.id }}" >> $GITHUB_ENV

    - name: Extract Branch Name
      id: extract_branch_name
      run: |
        branch_name=${{ github.ref }}
        branch_name=${branch_name#refs/heads/}
        echo "branch_name=${branch_name}" >> $GITHUB_ENV

    - name: Extract Commit Author Email
      id: extract_email
      run: echo "author_email=$(git log -1 --pretty=format:'%ae')" >> $GITHUB_ENV

    - name: Get GitHub Username from Email
      id: get_username
      run: |
        auth_header="Authorization: token ${{ secrets.PAT }}"
        email="${{ env.author_email }}"
        response=$(curl -s -H "$auth_header" https://api.github.com/search/users?q=$email+in:email)
        login=$(echo "$response" | jq -r '.items[0].login')
        echo "github_username=$login" >> $GITHUB_ENV

    - name: Create a new branch for cherry-picking
      run: |
        git checkout main
        git pull origin main
        git checkout -b "cherry-pick-${{ env.commit_sha }}"

    - name: Cherry-pick the commit onto the new branch
      run: |
        git cherry-pick ${{ env.commit_sha }} || {
          git checkout --theirs . &&
          git add . &&
          git cherry-pick --continue || git cherry-pick --skip
        }

    # make the name of the branch a variable
    - name: Push the new branch to origin
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}
      run: |
        git push origin cherry-pick-${{ env.commit_sha }}

    - name: Set up GitHub CLI
      run: sudo apt-get install gh

    - name: Authenticate with GitHub CLI
      run: gh auth login --with-token <<< ${{ secrets.PAT }}

    - name: Create Pull Request
      run: |
        gh pr create \
          --title "Cherry-pick commit ${{ env.commit_sha }} to main" \
          --body "This PR cherry-picks commit ${{ env.commit_sha }} from cherry-pick-${{ env.commit_sha }} into the main branch." \
          --base main \
          --head cherry-pick-${{ env.commit_sha }} \
          --assignee "${{ env.github_username }}"


